from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    return LaunchDescription([
        Node(
            package='sciurus17_examples',      
            executable='gripper_server',             
            name='gripper_server_right',      
            output='screen',
            arguments=['right']
        ),
        Node(
            package='sciurus17_examples',      
            executable='gripper_server',             
            name='gripper_server_left',      
            output='screen',
            arguments=['left']
        ),
        Node(
            package='sciurus17_examples',      
            executable='set_end_effector_pose_right_arm_server',             
            name='set_end_effector_pose_right_arm_server',      
            output='screen'
        ),
        Node(
            package='sciurus17_examples',      
            executable='set_end_effector_pose_left_arm_server',             
            name='set_end_effector_pose_left_arm_server',      
            output='screen'
        ),
        Node(
            package='sciurus17_examples',      
            executable='cartesian_pose_left_arm_waist_server',             
            name='cartesian_pose_left_arm_waist_server',      
            output='screen',
        ),
        Node(
            package='sciurus17_examples',      
            executable='cartesian_pose_right_arm_waist_server',             
            name='cartesian_pose_right_arm_waist_server',      
            output='screen',
        ),
        Node(
            package='sciurus17_examples',      
            executable='set_joint_values_left_arm_waist_server',             
            name='set_joint_values_left_arm_waist_server',      
            output='screen',
        ),
        Node(
            package='sciurus17_examples',      
            executable='set_joint_values_right_arm_waist_server',             
            name='set_joint_values_right_arm_waist_server',      
            output='screen',
        ),
        Node(
            package='sciurus17_examples',      
            executable='set_joint_values_neck_server',             
            name='set_joint_values_neck_server',      
            output='screen',
        ),
    ])
